-- Generated by npm run supabase:setup. For an EMPTY project only.
-- Paste the entire file into Supabase SQL Editor and run it once.
-- Auth users may already exist. App tables must not exist.
begin;
do $$ begin
  if to_regclass('public.players') is not null then
    raise exception 'App tables already exist. Apply only unapplied migrations instead.';
  end if;
end $$;

-- Migration: 001_initial_schema.sql
-- Mánudagsboltinn V1
-- Run this whole file once in Supabase -> SQL Editor.
-- V1 assumption: 4 small wins = 1 point; first team to 4 points wins a set.
-- Both values live on sessions, so they can be changed later without corrupting history.

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  nickname text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.seasons (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  starts_on date not null,
  ends_on date,
  is_active boolean not null default false
);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  season_id uuid references public.seasons(id) on delete set null,
  played_on date not null default current_date,
  status text not null default 'draft' check (status in ('draft','live','completed')),
  game_duration_seconds integer not null default 180 check (game_duration_seconds > 0),
  wins_per_point integer not null default 4 check (wins_per_point > 0),
  points_to_win_set integer not null default 4 check (points_to_win_set > 0),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.session_players (
  session_id uuid not null references public.sessions(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  primary key (session_id, player_id)
);

create table if not exists public.sets (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  set_no integer not null check (set_no > 0),
  status text not null default 'ready' check (status in ('ready','live','completed')),
  winning_team_id uuid,
  started_at timestamptz,
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, set_no)
);

create table if not exists public.set_teams (
  id uuid primary key default gen_random_uuid(),
  set_id uuid not null references public.sets(id) on delete cascade,
  name text not null,
  color text not null,
  sort_order integer not null default 0,
  unique (set_id, sort_order)
);

alter table public.sets
  drop constraint if exists sets_winning_team_id_fkey;
alter table public.sets
  add constraint sets_winning_team_id_fkey
  foreign key (winning_team_id) references public.set_teams(id) on delete set null;

create table if not exists public.set_team_members (
  set_id uuid not null references public.sets(id) on delete cascade,
  team_id uuid not null references public.set_teams(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete restrict,
  primary key (team_id, player_id),
  unique (set_id, player_id)
);

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  set_id uuid not null references public.sets(id) on delete cascade,
  game_no integer not null check (game_no > 0),
  holder_team_id uuid not null references public.set_teams(id) on delete restrict,
  challenger_team_id uuid not null references public.set_teams(id) on delete restrict,
  waiting_team_id uuid references public.set_teams(id) on delete set null,
  status text not null default 'ready' check (status in ('ready','live','paused','completed')),
  started_at timestamptz,
  ended_at timestamptz,
  duration_seconds integer not null default 180 check (duration_seconds > 0),
  remaining_seconds integer not null default 180 check (remaining_seconds >= 0),
  timer_started_at timestamptz,
  end_reason text check (end_reason is null or end_reason in ('goal','timeout','manual')),
  winning_team_id uuid references public.set_teams(id) on delete set null,
  exiting_team_id uuid references public.set_teams(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (set_id, game_no),
  check (holder_team_id <> challenger_team_id)
);

create table if not exists public.goals (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games(id) on delete cascade,
  team_id uuid not null references public.set_teams(id) on delete restrict,
  scorer_player_id uuid not null references public.players(id) on delete restrict,
  assist_player_id uuid references public.players(id) on delete restrict,
  seconds_elapsed integer not null default 0 check (seconds_elapsed >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  check (assist_player_id is null or assist_player_id <> scorer_player_id)
);

create index if not exists idx_sessions_played_on on public.sessions(played_on desc);
create index if not exists idx_sets_session on public.sets(session_id, set_no);
create index if not exists idx_set_teams_set on public.set_teams(set_id);
create index if not exists idx_set_team_members_set on public.set_team_members(set_id, player_id);
create index if not exists idx_games_set on public.games(set_id, game_no);
create index if not exists idx_goals_game on public.goals(game_id);
create index if not exists idx_goals_scorer on public.goals(scorer_player_id);
create index if not exists idx_goals_assist on public.goals(assist_player_id);
create unique index if not exists idx_one_active_goal_per_game on public.goals(game_id) where deleted_at is null;

create or replace view public.v_set_team_stats as
select
  s.id as set_id,
  s.session_id,
  st.id as team_id,
  st.name as team_name,
  count(g.id) filter (where g.status = 'completed' and g.winning_team_id = st.id) as small_wins,
  floor((count(g.id) filter (where g.status = 'completed' and g.winning_team_id = st.id))::numeric / se.wins_per_point)::int as points,
  mod((count(g.id) filter (where g.status = 'completed' and g.winning_team_id = st.id))::int, se.wins_per_point) as progress_wins,
  (s.winning_team_id = st.id) as is_winner,
  (
    s.status = 'completed'
    and s.winning_team_id is distinct from st.id
    and floor((count(g.id) filter (where g.status = 'completed' and g.winning_team_id = st.id))::numeric / se.wins_per_point)::int = se.points_to_win_set - 1
  ) as is_choke,
  (
    floor((count(g.id) filter (where g.status = 'completed' and g.winning_team_id = st.id))::numeric / se.wins_per_point)::int = 0
  ) as is_zero_point_set
from public.sets s
join public.sessions se on se.id = s.session_id
join public.set_teams st on st.set_id = s.id
left join public.games g on g.set_id = s.id
  and g.winning_team_id = st.id
  and g.status = 'completed'
group by s.id, s.session_id, s.status, s.winning_team_id, st.id, st.name, se.wins_per_point, se.points_to_win_set;

create or replace view public.v_set_player_stats as
select
  sts.set_id,
  sts.session_id,
  stm.player_id,
  sts.team_id,
  sts.team_name,
  sts.small_wins,
  sts.points,
  sts.progress_wins,
  sts.is_winner,
  sts.is_choke,
  sts.is_zero_point_set,
  coalesce((
    select count(*)::int
    from public.goals go
    join public.games ga on ga.id = go.game_id
    where ga.set_id = sts.set_id and go.scorer_player_id = stm.player_id and go.deleted_at is null
  ), 0) as goals,
  coalesce((
    select count(*)::int
    from public.goals go
    join public.games ga on ga.id = go.game_id
    where ga.set_id = sts.set_id and go.assist_player_id = stm.player_id and go.deleted_at is null
  ), 0) as assists
from public.v_set_team_stats sts
join public.set_team_members stm on stm.team_id = sts.team_id and stm.set_id = sts.set_id;

create or replace view public.v_session_player_stats as
select
  sp.session_id,
  sp.player_id,
  p.name,
  coalesce(sum(sps.points), 0)::int as points,
  coalesce(sum(sps.goals), 0)::int as goals,
  coalesce(sum(sps.assists), 0)::int as assists,
  count(*) filter (where sps.is_choke)::int as chokes,
  count(*) filter (where sps.is_zero_point_set)::int as zero_point_sets,
  (coalesce(sum(sps.points), 0) = 0) as is_nix_day
from public.session_players sp
join public.players p on p.id = sp.player_id
left join public.v_set_player_stats sps
  on sps.session_id = sp.session_id and sps.player_id = sp.player_id
group by sp.session_id, sp.player_id, p.name;

-- RLS: V1 backend is locked to authenticated Supabase users.
-- The local PWA still runs without Supabase credentials; auth UI comes in the next build layer.
do $$
declare t text;
begin
  foreach t in array array['players','seasons','sessions','session_players','sets','set_teams','set_team_members','games','goals']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists authenticated_all on public.%I', t);
    execute format('create policy authenticated_all on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;

-- Migration: 002_timer_persistence.sql
-- Safe upgrade if you already ran 001 from an earlier preview build.
alter table public.games add column if not exists remaining_seconds integer not null default 180;
alter table public.games add column if not exists timer_started_at timestamptz;

-- Migration: 003_season_analytics.sql
-- Season analytics layer for presentation, awards and balancing.
-- Safe to run after 001 + 002.


-- Backfill season rows for any existing sessions. A season runs Aug 1 -> Jul 31.
with season_years as (
  select distinct (extract(year from played_on)::int - case when extract(month from played_on)::int < 8 then 1 else 0 end) as start_year
  from public.sessions
), windows as (
  select start_year, make_date(start_year,8,1) as starts_on, make_date(start_year+1,7,31) as ends_on
  from season_years
)
insert into public.seasons (name, starts_on, ends_on, is_active)
select start_year::text || '/' || right((start_year+1)::text,2), starts_on, ends_on, current_date between starts_on and ends_on
from windows w
where not exists (select 1 from public.seasons s where s.starts_on = w.starts_on and s.ends_on = w.ends_on);

update public.sessions se
set season_id = s.id
from public.seasons s
where se.season_id is null and se.played_on between s.starts_on and coalesce(s.ends_on, '9999-12-31'::date);

create or replace view public.v_season_player_stats as
with set_rollup as (
  select
    se.season_id,
    sps.player_id,
    count(*)::int as sets_played,
    coalesce(sum(sps.small_wins),0)::int as small_wins,
    coalesce(sum(sps.points),0)::int as points,
    count(*) filter (where sps.is_winner)::int as set_wins,
    count(*) filter (where sps.is_choke)::int as chokes,
    count(*) filter (where sps.is_zero_point_set)::int as zero_point_sets,
    coalesce(sum(sps.goals),0)::int as goals,
    coalesce(sum(sps.assists),0)::int as assists
  from public.v_set_player_stats sps
  join public.sessions se on se.id = sps.session_id
  where se.status = 'completed' and se.season_id is not null
  group by se.season_id, sps.player_id
), night_rollup as (
  select
    se.season_id,
    v.player_id,
    count(*)::int as nights,
    count(*) filter (where v.is_nix_day)::int as nix_days,
    max(v.points)::int as best_night_points,
    max(v.goals)::int as best_night_goals,
    max(v.assists)::int as best_night_assists
  from public.v_session_player_stats v
  join public.sessions se on se.id = v.session_id
  where se.status = 'completed' and se.season_id is not null
  group by se.season_id, v.player_id
)
select
  sr.season_id,
  sr.player_id,
  p.name,
  nr.nights,
  sr.sets_played,
  sr.small_wins,
  sr.points,
  sr.set_wins,
  sr.goals,
  sr.assists,
  (sr.goals + sr.assists)::int as goal_contributions,
  sr.chokes,
  sr.zero_point_sets,
  nr.nix_days,
  nr.best_night_points,
  nr.best_night_goals,
  nr.best_night_assists,
  round(sr.points::numeric / nullif(nr.nights,0), 2) as points_per_night,
  round(sr.points::numeric / nullif(sr.sets_played,0), 2) as points_per_set,
  round(sr.set_wins::numeric / nullif(sr.sets_played,0), 4) as set_win_rate,
  round(sr.chokes::numeric / nullif(sr.set_wins + sr.chokes,0), 4) as choke_rate
from set_rollup sr
join night_rollup nr on nr.season_id = sr.season_id and nr.player_id = sr.player_id
join public.players p on p.id = sr.player_id;

create or replace view public.v_season_totals as
select
  se.season_id,
  count(distinct se.id)::int as nights,
  count(distinct st.id)::int as sets,
  count(distinct g.id)::int as games,
  count(distinct go.id) filter (where go.deleted_at is null)::int as goals,
  count(distinct sp.player_id)::int as players
from public.sessions se
left join public.session_players sp on sp.session_id = se.id
left join public.sets st on st.session_id = se.id and st.status = 'completed'
left join public.games g on g.set_id = st.id
left join public.goals go on go.game_id = g.id
where se.status = 'completed' and se.season_id is not null
group by se.season_id;

-- Backend award leaders. The PWA calculates the same concepts locally for offline use.
create or replace view public.v_season_award_leaders as
with metrics as (
  select season_id, player_id, name, 'points'::text as award_key, points::numeric as metric_value from public.v_season_player_stats
  union all select season_id, player_id, name, 'set_wins', set_wins::numeric from public.v_season_player_stats
  union all select season_id, player_id, name, 'goals', goals::numeric from public.v_season_player_stats
  union all select season_id, player_id, name, 'assists', assists::numeric from public.v_season_player_stats
  union all select season_id, player_id, name, 'contributions', goal_contributions::numeric from public.v_season_player_stats
  union all select season_id, player_id, name, 'nix_days', nix_days::numeric from public.v_season_player_stats where nix_days > 0
  union all select season_id, player_id, name, 'chokes', chokes::numeric from public.v_season_player_stats where chokes > 0
  union all select season_id, player_id, name, 'zero_point_sets', zero_point_sets::numeric from public.v_season_player_stats where zero_point_sets > 0
), ranked as (
  select *, dense_rank() over (partition by season_id, award_key order by metric_value desc) as rank
  from metrics
)
select season_id, award_key, player_id, name, metric_value
from ranked
where rank = 1;

-- Migration: 004_product_spec_v1.sql
-- Bring the deployed schema in line with docs/PRODUCT_SPEC.md.
-- Raw event facts remain authoritative; all standings stay derived.

do $$ begin
  create type public.player_role as enum ('REGULAR', 'SUBSTITUTE');
exception when duplicate_object then null; end $$;

create table if not exists public.player_role_periods (
  id uuid primary key,
  season_id uuid not null references public.seasons(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  role public.player_role not null,
  valid_from date not null,
  valid_to date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valid_to is null or valid_to >= valid_from)
);
create index if not exists idx_role_period_lookup on public.player_role_periods(season_id, player_id, valid_from);

alter table public.session_players add column if not exists role_at_session public.player_role;
update public.session_players set role_at_session = 'SUBSTITUTE' where role_at_session is null;
alter table public.session_players alter column role_at_session set not null;

alter table public.games add column if not exists incumbent_team_id uuid references public.set_teams(id) on delete set null;
alter table public.goals add column if not exists event_type text not null default 'GOAL';
alter table public.goals drop constraint if exists goals_event_type_check;
alter table public.goals add constraint goals_event_type_check check (event_type in ('GOAL', 'OWN_GOAL'));
alter table public.goals drop constraint if exists goals_own_goal_assist_check;
alter table public.goals add constraint goals_own_goal_assist_check check (event_type <> 'OWN_GOAL' or assist_player_id is null);

create table if not exists public.timer_events (
  id uuid primary key,
  game_id uuid not null references public.games(id) on delete cascade,
  event_type text not null check (event_type in ('START','PAUSE','RESUME','EXPIRE')),
  occurred_at timestamptz not null
);
create index if not exists idx_timer_events_game on public.timer_events(game_id, occurred_at);

-- The V1 rule is exactly first to four mini-game wins.
alter table public.sessions alter column wins_per_point set default 1;
update public.sessions set wins_per_point = 1 where wins_per_point = 4 and points_to_win_set = 4;

alter table public.player_role_periods enable row level security;
alter table public.timer_events enable row level security;
drop policy if exists authenticated_all on public.player_role_periods;
create policy authenticated_all on public.player_role_periods for all to authenticated using (true) with check (true);
drop policy if exists authenticated_all on public.timer_events;
create policy authenticated_all on public.timer_events for all to authenticated using (true) with check (true);
grant select, insert, update, delete on public.player_role_periods, public.timer_events to authenticated;

-- Migration: 005_session_backfills.sql
-- Aggregate-only entry for a played session where exact event order was not recorded.
-- The JSON contains known team rosters, per-round team goals and player goal totals.
-- It must never be expanded into invented mini-game events.
create table if not exists public.session_backfills (
  session_id uuid primary key references public.sessions(id) on delete cascade,
  source_kind text not null default 'AGGREGATE' check (source_kind = 'AGGREGATE'),
  assists_recorded boolean not null default false check (assists_recorded = false),
  teams jsonb not null,
  rounds jsonb not null,
  player_goals jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.session_players add column if not exists team_code text check (team_code in ('A','B','C'));
alter table public.session_backfills enable row level security;
drop policy if exists authenticated_all on public.session_backfills;
create policy authenticated_all on public.session_backfills for all to authenticated using (true) with check (true);
grant select, insert, update, delete on public.session_backfills to authenticated;

-- Migration: 006_timer_precision.sql
-- Preserve sub-second pause/resume accuracy without changing existing values.
alter table public.games alter column remaining_seconds type double precision;
alter table public.goals alter column seconds_elapsed type double precision;

-- Migration: 007_secure_atomic_sync.sql
-- V1 cloud contract: one recorder, atomic ordered writes, retry receipts and
-- raw session recovery snapshots. Run after 001-006; no historical import.
create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.app_admins enable row level security;
revoke all on public.app_admins from public, anon, authenticated;
grant select on public.app_admins to authenticated;
create policy read_own_membership on public.app_admins for select to authenticated
  using (user_id = (select auth.uid()));

create or replace function public.is_app_admin() returns boolean
language sql stable security invoker set search_path = '' as $$
  select exists (select 1 from public.app_admins where user_id = (select auth.uid()));
$$;
revoke all on function public.is_app_admin() from public, anon;
grant execute on function public.is_app_admin() to authenticated;

create table public.sync_operations (
  id uuid primary key,
  applied_at timestamptz not null default now()
);
create table public.session_snapshots (
  session_id uuid primary key references public.sessions(id) on delete cascade,
  schema_version integer not null default 1 check (schema_version = 1),
  payload jsonb not null,
  updated_at timestamptz not null default now()
);

do $$ declare t text; begin
  foreach t in array array['players','seasons','player_role_periods','sessions',
    'session_players','session_backfills','sets','set_teams','set_team_members',
    'games','goals','timer_events','sync_operations','session_snapshots'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists authenticated_all on public.%I', t);
    execute format('revoke all on public.%I from public, anon, authenticated', t);
    execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    execute format('create policy admin_access on public.%I for all to authenticated using ((select public.is_app_admin())) with check ((select public.is_app_admin()))', t);
  end loop;
end $$;

-- Older analytics are not the V1 role-snapshot standings. Keep them out of the
-- browser API, and prevent owner-privilege views bypassing table RLS.
do $$ declare v text; begin
  foreach v in array array['v_set_team_stats','v_set_player_stats',
    'v_session_player_stats','v_season_player_stats','v_season_totals',
    'v_season_award_leaders'] loop
    execute format('alter view public.%I set (security_invoker = true)', v);
    execute format('revoke all on public.%I from public, anon, authenticated', v);
  end loop;
end $$;

-- A restored completed set may precede its teams within a single batch.
alter table public.sets alter constraint sets_winning_team_id_fkey
  deferrable initially deferred;

create or replace function public.get_sync_state() returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare result jsonb := '{}'::jsonb; t text; rows jsonb;
begin
  if not public.is_app_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;
  foreach t in array array['players','seasons','player_role_periods','sessions',
    'session_players','session_backfills','sets','set_teams','set_team_members',
    'games','goals','timer_events'] loop
    execute format('select coalesce(jsonb_agg(to_jsonb(r)), ''[]''::jsonb) from public.%I r', t) into rows;
    result := result || jsonb_build_object(t, rows);
  end loop;
  return jsonb_build_object('schema_version', 1, 'tables', result);
end $$;

create or replace function public.apply_sync_batch(operations jsonb) returns integer
language plpgsql security invoker set search_path = '' as $$
declare
  item jsonb; t text; body jsonb; columns_sql text; values_sql text;
  updates_sql text; keys_sql text; applied integer := 0;
begin
  if not public.is_app_admin() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;
  if jsonb_typeof(operations) is distinct from 'array' then
    raise exception 'Expected operations array';
  end if;
  -- Serialize retries from separate tabs/devices before checking receipts.
  perform pg_advisory_xact_lock(724019260);
  for item in select value from jsonb_array_elements(operations) loop
    if exists (select 1 from public.sync_operations where id = (item->>'id')::uuid) then
      continue;
    end if;
    t := item->>'table';
    if t is null or t <> all(array['players','seasons','player_role_periods',
      'sessions','session_players','session_backfills','sets','set_teams',
      'set_team_members','games','goals','timer_events']) then
      raise exception 'Unsupported sync table';
    end if;
    if item->>'operation' = 'delete' then
      -- Current recorder deletes only these parent/event records. Cascades
      -- remove their children, including prepared games after Undo.
      if t <> all(array['games','sets','timer_events']) then
        raise exception 'Unsupported sync delete';
      end if;
      execute format('delete from public.%I where id = $1', t)
        using (item->>'entity_id')::uuid;
    elsif item->>'operation' = 'upsert' then
      body := item->'payload';
      if jsonb_typeof(body) is distinct from 'object' or body = '{}'::jsonb then
        raise exception 'Expected row object';
      end if;
      keys_sql := case t
        when 'session_players' then 'session_id, player_id'
        when 'set_team_members' then 'team_id, player_id'
        when 'session_backfills' then 'session_id'
        else 'id' end;
      -- Only supplied columns are inserted: omitted values retain SQL defaults.
      -- Identifiers are quoted, table names allow-listed, data is parameterized.
      select string_agg(format('%I', key), ', ' order by key),
        string_agg(format('r.%I', key), ', ' order by key),
        string_agg(format('%I = excluded.%I', key, key), ', ' order by key)
        into columns_sql, values_sql, updates_sql from jsonb_object_keys(body) key;
      execute format('insert into public.%I (%s) select %s from jsonb_populate_record(null::public.%I, $1) r on conflict (%s) do update set %s',
        t, columns_sql, values_sql, t, keys_sql, updates_sql) using body;
    else
      raise exception 'Unsupported sync operation';
    end if;
    insert into public.sync_operations(id) values ((item->>'id')::uuid);
    applied := applied + 1;
  end loop;

  -- A disposable recovery copy of raw facts, never primary aggregate truth.
  -- Rebuilt in this transaction, so it cannot describe half an action.
  insert into public.session_snapshots(session_id, payload, updated_at)
  select s.id, jsonb_build_object(
    'session', to_jsonb(s),
    'season', (select to_jsonb(se) from public.seasons se where se.id = s.season_id),
    'players', (select coalesce(jsonb_agg(to_jsonb(p)), '[]') from public.players p
      join public.session_players sp on sp.player_id = p.id where sp.session_id = s.id),
    'session_players', (select coalesce(jsonb_agg(to_jsonb(sp)), '[]') from public.session_players sp where sp.session_id = s.id),
    'session_backfills', (select coalesce(jsonb_agg(to_jsonb(b)), '[]') from public.session_backfills b where b.session_id = s.id),
    'sets', (select coalesce(jsonb_agg(to_jsonb(st)), '[]') from public.sets st where st.session_id = s.id),
    'set_teams', (select coalesce(jsonb_agg(to_jsonb(team_row)), '[]') from public.set_teams team_row join public.sets st on st.id = team_row.set_id where st.session_id = s.id),
    'set_team_members', (select coalesce(jsonb_agg(to_jsonb(m)), '[]') from public.set_team_members m join public.sets st on st.id = m.set_id where st.session_id = s.id),
    'games', (select coalesce(jsonb_agg(to_jsonb(g)), '[]') from public.games g join public.sets st on st.id = g.set_id where st.session_id = s.id),
    'goals', (select coalesce(jsonb_agg(to_jsonb(go)), '[]') from public.goals go join public.games g on g.id = go.game_id join public.sets st on st.id = g.set_id where st.session_id = s.id),
    'timer_events', (select coalesce(jsonb_agg(to_jsonb(e)), '[]') from public.timer_events e join public.games g on g.id = e.game_id join public.sets st on st.id = g.set_id where st.session_id = s.id)
  ), now() from public.sessions s
  on conflict (session_id) do update set payload = excluded.payload, updated_at = excluded.updated_at;
  return applied;
end $$;

revoke all on function public.get_sync_state() from public, anon;
revoke all on function public.apply_sync_batch(jsonb) from public, anon;
grant execute on function public.get_sync_state(), public.apply_sync_batch(jsonb) to authenticated;

-- Migration: 008_shared_recording_access.sql
-- Shared recording access. Apply after 007 on the existing project.
-- Authentication is Supabase Auth; a shared recorder is never an app_admin.
create table public.app_recorders (
  user_id uuid primary key references auth.users(id) on delete cascade
);
alter table public.app_recorders enable row level security;
revoke all on public.app_recorders from public, anon, authenticated;
grant select on public.app_recorders to authenticated;
create policy own_recorder_membership on public.app_recorders for select to authenticated
  using (user_id = (select auth.uid()));

create function public.is_app_recorder() returns boolean
language sql stable security invoker set search_path = '' as $$
  select exists(select 1 from public.app_recorders where user_id = (select auth.uid()))
    and not public.is_app_admin();
$$;

create table public.recording_window (
  id boolean primary key default true check (id),
  played_on date not null,
  season_id uuid not null references public.seasons(id),
  is_open boolean not null default false
);
alter table public.recording_window enable row level security;
revoke all on public.recording_window from public, anon, authenticated;
grant select, insert, update, delete on public.recording_window to authenticated;
create policy admin_window on public.recording_window for all to authenticated
  using ((select public.is_app_admin())) with check ((select public.is_app_admin()));

create function public.is_recording_night(night date, season uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select public.is_app_recorder() and exists (
    select 1 from public.recording_window w
    where w.is_open and w.played_on = night and w.season_id = season
  );
$$;
create function public.can_access_session(session uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select public.is_app_admin() or exists(select 1 from public.sessions s
    where s.id = session and public.is_recording_night(s.played_on, s.season_id));
$$;
create function public.can_access_set(set_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select public.is_app_admin() or exists(select 1 from public.sets s
    where s.id = set_id and public.can_access_session(s.session_id));
$$;
create function public.can_access_team(team_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select public.is_app_admin() or exists(select 1 from public.set_teams t
    where t.id = team_id and public.can_access_set(t.set_id));
$$;
create function public.can_access_game(game_id uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select public.is_app_admin() or exists(select 1 from public.games g
    where g.id = game_id and public.can_access_set(g.set_id));
$$;

create function public.get_app_access() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare w public.recording_window;
begin
  if public.is_app_admin() then return jsonb_build_object('role', 'admin'); end if;
  if not public.is_app_recorder() then
    raise exception 'Access denied' using errcode = '42501';
  end if;
  select * into w from public.recording_window where is_open;
  return jsonb_build_object('role', 'recorder', 'playedOn', w.played_on, 'seasonId', w.season_id);
end $$;

create function public.set_recording_window(night date, season uuid, open boolean) returns void
language plpgsql security invoker set search_path = '' as $$
begin
  if not public.is_app_admin() then raise exception 'Admin access required' using errcode = '42501'; end if;
  if not exists(select 1 from public.seasons s where s.id = season
    and night >= s.starts_on and (s.ends_on is null or night <= s.ends_on)) then
    raise exception 'Date must belong to the selected season';
  end if;
  insert into public.recording_window(id, played_on, season_id, is_open)
  values (true, night, season, open)
  on conflict(id) do update set played_on = excluded.played_on, season_id = excluded.season_id, is_open = excluded.is_open;
end $$;

-- Roster metadata only, never historical membership or season results.
create function public.get_recorder_context() returns jsonb
language plpgsql stable security definer set search_path = '' as $$
declare w public.recording_window;
begin
  if not public.is_app_recorder() then raise exception 'Recorder access required' using errcode = '42501'; end if;
  select * into w from public.recording_window where is_open;
  if w.season_id is null then return jsonb_build_object('seasons','[]'::jsonb,'player_role_periods','[]'::jsonb); end if;
  return jsonb_build_object(
    'seasons', jsonb_build_array(jsonb_build_object('id', w.season_id, 'name', 'Skráning',
      'starts_on', w.played_on, 'ends_on', w.played_on, 'is_active', true)),
    'player_role_periods', (select coalesce(jsonb_agg(to_jsonb(r)), '[]') from (
      select p.id, p.season_id, p.player_id, p.role, w.played_on as valid_from,
        w.played_on as valid_to, p.created_at, p.updated_at
      from public.player_role_periods p where p.season_id = w.season_id
        and p.valid_from <= w.played_on and (p.valid_to is null or p.valid_to >= w.played_on)
    ) r)
  );
end $$;

create policy recorder_players_read on public.players for select to authenticated
  using (public.is_app_recorder() and is_active);
create policy recorder_players_insert on public.players for insert to authenticated
  with check (public.is_app_recorder() and is_active);
create policy recorder_sessions on public.sessions for all to authenticated
  using (public.is_recording_night(played_on, season_id))
  with check (public.is_recording_night(played_on, season_id));
create policy recorder_attendance on public.session_players for all to authenticated
  using (public.can_access_session(session_id)) with check (public.can_access_session(session_id));
create policy recorder_sets on public.sets for all to authenticated
  using (public.can_access_session(session_id))
  with check (public.can_access_session(session_id) and (winning_team_id is null or public.can_access_team(winning_team_id)));
create policy recorder_teams on public.set_teams for all to authenticated
  using (public.can_access_set(set_id)) with check (public.can_access_set(set_id));
create policy recorder_members on public.set_team_members for all to authenticated
  using (public.can_access_set(set_id))
  with check (public.can_access_set(set_id) and public.can_access_team(team_id));
create policy recorder_games on public.games for all to authenticated
  using (public.can_access_set(set_id))
  with check (public.can_access_set(set_id) and public.can_access_team(holder_team_id)
    and public.can_access_team(challenger_team_id)
    and (waiting_team_id is null or public.can_access_team(waiting_team_id))
    and (incumbent_team_id is null or public.can_access_team(incumbent_team_id))
    and (winning_team_id is null or public.can_access_team(winning_team_id))
    and (exiting_team_id is null or public.can_access_team(exiting_team_id)));
create policy recorder_goals on public.goals for all to authenticated
  using (public.can_access_game(game_id))
  with check (public.can_access_game(game_id) and public.can_access_team(team_id));
create policy recorder_timer on public.timer_events for all to authenticated
  using (public.can_access_game(game_id)) with check (public.can_access_game(game_id));

-- A recorder selects attendance, not competition eligibility. Derive new role
-- snapshots from the administrator's periods and preserve them on updates.
create function public.protect_recorder_role_snapshot() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  if public.is_app_recorder() then
    if tg_op = 'UPDATE' then
      new.role_at_session := old.role_at_session;
    else
      select coalesce((select p.role from public.player_role_periods p
        where p.player_id = new.player_id and p.season_id = s.season_id
          and p.valid_from <= s.played_on and (p.valid_to is null or p.valid_to >= s.played_on)
        order by p.valid_from desc, p.created_at desc limit 1), 'SUBSTITUTE'::public.player_role)
      into new.role_at_session from public.sessions s where s.id = new.session_id;
    end if;
  end if;
  return new;
end $$;
revoke all on function public.protect_recorder_role_snapshot() from public, anon, authenticated;
create trigger protect_recorder_role_snapshot before insert or update on public.session_players
  for each row execute function public.protect_recorder_role_snapshot();

alter table public.sync_operations add column user_id uuid default auth.uid() references auth.users(id);
create policy recorder_receipts on public.sync_operations for select to authenticated
  using (public.is_app_recorder() and user_id = (select auth.uid()));
create policy recorder_receipts_insert on public.sync_operations for insert to authenticated
  with check (public.is_app_recorder() and user_id = (select auth.uid()));

-- Every new callable helper has explicit privileges and a fixed search_path.
do $$ declare f regprocedure; begin
  foreach f in array array[
    'public.is_app_recorder()'::regprocedure,
    'public.is_recording_night(date,uuid)'::regprocedure,
    'public.can_access_session(uuid)'::regprocedure,
    'public.can_access_set(uuid)'::regprocedure,
    'public.can_access_team(uuid)'::regprocedure,
    'public.can_access_game(uuid)'::regprocedure,
    'public.get_app_access()'::regprocedure,
    'public.get_recorder_context()'::regprocedure,
    'public.set_recording_window(date,uuid,boolean)'::regprocedure
  ] loop
    execute format('revoke all on function %s from public, anon', f);
    execute format('grant execute on function %s to authenticated', f);
  end loop;
end $$;

-- This definer writes recovery copies but never returns protected history.
create function public.refresh_accessible_snapshots() returns void
language plpgsql security definer set search_path = '' as $$
begin
  if not public.is_app_admin() and not public.is_app_recorder() then
    raise exception 'Access denied' using errcode = '42501';
  end if;
  insert into public.session_snapshots(session_id, payload, updated_at)
  select s.id, jsonb_build_object(
    'session', to_jsonb(s),
    'season', (select to_jsonb(se) from public.seasons se where se.id = s.season_id),
    'players', (select coalesce(jsonb_agg(to_jsonb(p)), '[]') from public.players p
      join public.session_players sp on sp.player_id = p.id where sp.session_id = s.id),
    'session_players', (select coalesce(jsonb_agg(to_jsonb(sp)), '[]') from public.session_players sp where sp.session_id = s.id),
    'session_backfills', (select coalesce(jsonb_agg(to_jsonb(b)), '[]') from public.session_backfills b where b.session_id = s.id),
    'sets', (select coalesce(jsonb_agg(to_jsonb(st)), '[]') from public.sets st where st.session_id = s.id),
    'set_teams', (select coalesce(jsonb_agg(to_jsonb(team_row)), '[]') from public.set_teams team_row join public.sets st on st.id = team_row.set_id where st.session_id = s.id),
    'set_team_members', (select coalesce(jsonb_agg(to_jsonb(m)), '[]') from public.set_team_members m join public.sets st on st.id = m.set_id where st.session_id = s.id),
    'games', (select coalesce(jsonb_agg(to_jsonb(g)), '[]') from public.games g join public.sets st on st.id = g.set_id where st.session_id = s.id),
    'goals', (select coalesce(jsonb_agg(to_jsonb(go)), '[]') from public.goals go join public.games g on g.id = go.game_id join public.sets st on st.id = g.set_id where st.session_id = s.id),
    'timer_events', (select coalesce(jsonb_agg(to_jsonb(e)), '[]') from public.timer_events e join public.games g on g.id = e.game_id join public.sets st on st.id = g.set_id where st.session_id = s.id)
  ), now() from public.sessions s where public.can_access_session(s.id)
  on conflict (session_id) do update set payload = excluded.payload, updated_at = excluded.updated_at;
end $$;
revoke all on function public.refresh_accessible_snapshots() from public, anon;
grant execute on function public.refresh_accessible_snapshots() to authenticated;

create or replace function public.apply_sync_batch(operations jsonb) returns integer
language plpgsql security invoker set search_path = '' as $$
declare
  item jsonb; t text; body jsonb; columns_sql text; values_sql text;
  updates_sql text; keys_sql text; applied integer := 0;
begin
  if not public.is_app_admin() and not public.is_app_recorder() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;
  if jsonb_typeof(operations) is distinct from 'array' then
    raise exception 'Expected operations array';
  end if;
  -- Serialize retries from separate tabs/devices before checking receipts.
  perform pg_advisory_xact_lock(724019260);
  for item in select value from jsonb_array_elements(operations) loop
    if exists (select 1 from public.sync_operations where id = (item->>'id')::uuid) then
      continue;
    end if;
    t := item->>'table';
    if t is null or t <> all(array['players','seasons','player_role_periods',
      'sessions','session_players','session_backfills','sets','set_teams',
      'set_team_members','games','goals','timer_events']) then
      raise exception 'Unsupported sync table';
    end if;
    if item->>'operation' = 'delete' then
      -- Current recorder deletes only these parent/event records. Cascades
      -- remove their children, including prepared games after Undo.
      if t <> all(array['games','sets','timer_events']) then
        raise exception 'Unsupported sync delete';
      end if;
      if public.is_app_recorder() and not (
        (t = 'games' and public.can_access_game((item->>'entity_id')::uuid)) or
        (t = 'sets' and public.can_access_set((item->>'entity_id')::uuid)) or
        (t = 'timer_events' and exists(select 1 from public.timer_events e
          where e.id = (item->>'entity_id')::uuid and public.can_access_game(e.game_id)))
      ) then raise exception 'Delete outside recording night' using errcode = '42501'; end if;
      execute format('delete from public.%I where id = $1', t)
        using (item->>'entity_id')::uuid;
    elsif item->>'operation' = 'upsert' then
      body := item->'payload';
      if jsonb_typeof(body) is distinct from 'object' or body = '{}'::jsonb then
        raise exception 'Expected row object';
      end if;
      keys_sql := case t
        when 'session_players' then 'session_id, player_id'
        when 'set_team_members' then 'team_id, player_id'
        when 'session_backfills' then 'session_id'
        else 'id' end;
      -- Only supplied columns are inserted: omitted values retain SQL defaults.
      -- Identifiers are quoted, table names allow-listed, data is parameterized.
      select string_agg(format('%I', key), ', ' order by key),
        string_agg(format('r.%I', key), ', ' order by key),
        string_agg(format('%I = excluded.%I', key, key), ', ' order by key)
        into columns_sql, values_sql, updates_sql from jsonb_object_keys(body) key;
      execute format('insert into public.%I (%s) select %s from jsonb_populate_record(null::public.%I, $1) r on conflict (%s) do update set %s',
        t, columns_sql, values_sql, t, keys_sql, updates_sql) using body;
    else
      raise exception 'Unsupported sync operation';
    end if;
    insert into public.sync_operations(id) values ((item->>'id')::uuid);
    applied := applied + 1;
  end loop;

  perform public.refresh_accessible_snapshots();
  return applied;
end $$;

create or replace function public.get_sync_state() returns jsonb
language plpgsql stable security invoker set search_path = '' as $$
declare result jsonb := '{}'::jsonb; t text; rows jsonb;
begin
  if not public.is_app_admin() and not public.is_app_recorder() then
    raise exception 'Admin access required' using errcode = '42501';
  end if;
  foreach t in array array['players','seasons','player_role_periods','sessions',
    'session_players','session_backfills','sets','set_teams','set_team_members',
    'games','goals','timer_events'] loop
    execute format('select coalesce(jsonb_agg(to_jsonb(r)), ''[]''::jsonb) from public.%I r', t) into rows;
    result := result || jsonb_build_object(t, rows);
  end loop;
  if public.is_app_recorder() then
    result := result || public.get_recorder_context();
  end if;
  return jsonb_build_object('schema_version', 1, 'tables', result);
end $$;

commit;
