import { readFileSync, readdirSync, writeFileSync } from 'node:fs'

const directory = new URL('../supabase/migrations/', import.meta.url)
const files = readdirSync(directory).filter(name => /^\d+.*\.sql$/.test(name)).sort()
const header = `-- Generated by npm run supabase:setup. For an EMPTY project only.
-- Paste the entire file into Supabase SQL Editor and run it once.
-- Auth users may already exist. App tables must not exist.
begin;
do $$ begin
  if to_regclass('public.players') is not null then
    raise exception 'App tables already exist. Apply only unapplied migrations instead.';
  end if;
end $$;
`
const sql = files.map(name => `\n-- Migration: ${name}\n${readFileSync(new URL(name, directory), 'utf8').trim()}\n`).join('')
writeFileSync(new URL('../supabase/setup-empty-project.sql', import.meta.url), `${header}${sql}\ncommit;\n`, 'utf8')
console.log(`Prepared ${files.length} migrations in supabase/setup-empty-project.sql`)
